import { Router } from "express";
import auth from "../../middlewares/auth";
import validateRequest from "../../middlewares/validateRequest";
import { PERMISSIONS } from "../User/user.constant";
import { InvoiceController } from "./invoice.controller";
import { InvoiceValidation } from "./invoice.validation";
const router = Router();
router.post("/cases/:caseId", auth(PERMISSIONS.INVOICE_GENERATE), validateRequest(InvoiceValidation.caseInvoiceValidationSchema), InvoiceController.generateInvoice);
router.get("/cases/:caseId", auth(PERMISSIONS.INVOICE_READ), validateRequest(InvoiceValidation.caseInvoiceValidationSchema), InvoiceController.listInvoices);
router.get("/:id", auth(PERMISSIONS.INVOICE_READ), validateRequest(InvoiceValidation.invoiceIdValidationSchema), InvoiceController.getInvoice);
export const InvoiceRoutes = router;
